[package]
name = "tm20-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false
description = "Print a tm20-set Sheet or a CommonMark file on the TM-T20III"

[[bin]]
name = "tm20-set"
path = "src/main.rs"

[dependencies]
tm20 = { workspace = true }
tm20-set = { workspace = true }
tm20-md = { workspace = true }

[lints]
workspace = true
